import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Heart, MessageCircle, Share2 } from "lucide-react";

const Community = () => {
  const posts = [
    {
      id: 1,
      user: {
        name: "Sarah Johnson",
        avatar: "https://i.pravatar.cc/150?img=1",
      },
      image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
      caption: "Spring vibes with this new outfit combination! 🌸",
      likes: 234,
      comments: 45,
    },
    {
      id: 2,
      user: {
        name: "Mike Chen",
        avatar: "https://i.pravatar.cc/150?img=2",
      },
      image: "https://images.unsplash.com/photo-1483985988355-763728e1935b",
      caption: "Loving this casual weekend look generated by StyleAI! 👕",
      likes: 189,
      comments: 32,
    },
  ];

  return (
    <div className="container py-8 space-y-8 animate-fade-up">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold">Community</h1>
        <p className="text-lg text-muted-foreground">
          Share your style and get inspired by others
        </p>
      </div>

      <div className="max-w-2xl mx-auto space-y-8">
        <Card className="p-4">
          <div className="flex items-center gap-4">
            <Input placeholder="Share your style journey..." />
            <Button>Post</Button>
          </div>
        </Card>

        {posts.map((post) => (
          <Card key={post.id} className="overflow-hidden">
            <div className="p-4 flex items-center gap-3">
              <img
                src={post.user.avatar}
                alt={post.user.name}
                className="w-10 h-10 rounded-full"
              />
              <span className="font-medium">{post.user.name}</span>
            </div>
            
            <img
              src={post.image}
              alt="Post"
              className="w-full aspect-square object-cover"
            />
            
            <div className="p-4 space-y-4">
              <div className="flex gap-4">
                <Button variant="ghost" size="sm">
                  <Heart className="h-5 w-5 mr-2" />
                  {post.likes}
                </Button>
                <Button variant="ghost" size="sm">
                  <MessageCircle className="h-5 w-5 mr-2" />
                  {post.comments}
                </Button>
                <Button variant="ghost" size="sm">
                  <Share2 className="h-5 w-5 mr-2" />
                  Share
                </Button>
              </div>
              <p>{post.caption}</p>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default Community;